name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: creditrisk-azure-app   # replace if different
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install -r credit_risk/requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        username: ${{ secrets.AZURE_WEBAPP_USERNAME }}
        password: ${{ secrets.AZURE_WEBAPP_PASSWORD }}
        package: credit_risk
        startup-command: --chdir credit_risk gunicorn --bind=0.0.0.0 --timeout 600 app:app
